-- 1) DROP constraint cũ
ALTER TABLE SUBSCRIPTION_PACKAGE
DROP CONSTRAINT DF_SUBSCRIPTION_PACKAGE_update_at;
GO

-- 2) DROP column cũ
ALTER TABLE SUBSCRIPTION_PACKAGE
DROP COLUMN update_at;
GO

-- 3) ADD column mới kèm default
ALTER TABLE SUBSCRIPTION_PACKAGE
ADD update_at DATETIME2(0) NULL
    CONSTRAINT DF_SUBSCRIPTION_PACKAGE_update_at
    DEFAULT SYSUTCDATETIME();
GO



ALTER TABLE USER_SUBSCRIPTION
  ALTER COLUMN start_date DATETIME2(0) NULL;
GO
ALTER TABLE USER_SUBSCRIPTION
  ALTER COLUMN end_date   DATETIME2(0) NULL;
GO
ALTER TABLE PAYMENT
  ALTER COLUMN payment_date DATETIME2(0) NOT NULL;
GO
ALTER TABLE NOTIFICATION
  ALTER COLUMN created_at DATETIME2(0) NOT NULL;
GO


