-- Xóa bảng phụ thuộc trước (có FK đến CUSTOMER)
DELETE FROM COACHING_MESSAGE;
DELETE FROM COACHING_SESSION;
DELETE FROM NOTIFICATION;
DELETE FROM NOTIFICATION_PREFERENCE;
DELETE FROM USER_ACHIEVEMENT;
DELETE FROM PROGRESS_TRACKER;
DELETE FROM DAILY_SMOKING_SUMMARY;
DELETE FROM SMOKING_LOG;
DELETE FROM PLAN_FEEDBACK;
DELETE FROM COACH_PLAN_ASSIGNMENT;
DELETE FROM CESSATION_PLAN;
DELETE FROM COACH;
DELETE FROM USER_SUBSCRIPTION;
DELETE FROM PAYMENT;
DELETE FROM USER_PROFILE;
DELETE FROM USER_LOGIN;

-- Delete CUSTOMER
DELETE FROM CUSTOMER;

-- Reset các bảng đã từng insert
DBCC CHECKIDENT ('CUSTOMER', RESEED, 0);
DBCC CHECKIDENT ('USER_LOGIN', RESEED, 0);
DBCC CHECKIDENT ('USER_PROFILE', RESEED, 0);
DBCC CHECKIDENT ('USER_SUBSCRIPTION', RESEED, 0);
DBCC CHECKIDENT ('PAYMENT', RESEED, 0);
DBCC CHECKIDENT ('COACH', RESEED, 0);
DBCC CHECKIDENT ('CESSATION_PLAN', RESEED, 0);
DBCC CHECKIDENT ('COACH_PLAN_ASSIGNMENT', RESEED, 0);
DBCC CHECKIDENT ('PLAN_FEEDBACK', RESEED, 0);
DBCC CHECKIDENT ('PLAN_MILESTONE', RESEED, 0);
DBCC CHECKIDENT ('SMOKING_LOG', RESEED, 0);
DBCC CHECKIDENT ('DAILY_SMOKING_SUMMARY', RESEED, 0);
DBCC CHECKIDENT ('PROGRESS_TRACKER', RESEED, 0);
DBCC CHECKIDENT ('USER_ACHIEVEMENT', RESEED, 0);
DBCC CHECKIDENT ('NOTIFICATION', RESEED, 0);
DBCC CHECKIDENT ('NOTIFICATION_PREFERENCE', RESEED, 0);
DBCC CHECKIDENT ('COACHING_SESSION', RESEED, 0);
DBCC CHECKIDENT ('COACHING_MESSAGE', RESEED, 0);
DBCC CHECKIDENT ('COMMUNITY_POST', RESEED, 0);
DBCC CHECKIDENT ('POST_COMMENT', RESEED, 0);
DBCC CHECKIDENT ('RESOURCE', RESEED, 0);
DBCC CHECKIDENT ('FEEDBACK', RESEED, 0);
DBCC CHECKIDENT ('RESET_TOKENS', RESEED, 0);
DBCC CHECKIDENT ('WEEKLY_QUOTA', RESEED, 0);