-- Xóa Database Chính thức
ALTER DATABASE SmokingSessation SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE SmokingSessation;

-- Xóa Database Cũ
ALTER DATABASE Quit_Smoking SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE Quit_Smoking;

-- Lệnh để set UserId Thành Admin (làm tay đi: tạo thành khoản mới rồi vô database set thành admin)
UPDATE CUSTOMER
SET user_role = 'admin'
WHERE email = 'admin@gmail.com';

-- Xóa dữ liệu từ bảng phụ thuộc trước
DELETE FROM POST_COMMENT;
DELETE FROM COMMUNITY_POST;
DELETE FROM NOTIFICATION_PREFERENCE;
DELETE FROM NOTIFICATION;
DELETE FROM USER_ACHIEVEMENT;
DELETE FROM ACHIEVEMENT;
DELETE FROM COACHING_MESSAGE;
DELETE FROM COACHING_SESSION;
DELETE FROM COACH_SCHEDULE;
DELETE FROM FTND_RESULT;
DELETE FROM PROGRESS_TRACKER;
DELETE FROM DAILY_SMOKING_SUMMARY;
DELETE FROM SMOKING_LOG;
DELETE FROM PLAN_FEEDBACK;
DELETE FROM PLAN_MILESTONE;
DELETE FROM WEEKLY_QUOTA;
DELETE FROM CESSATION_PLAN;
DELETE FROM PLAN_TEMPLATE;
DELETE FROM COACH;
DELETE FROM PAYMENT;
DELETE FROM USER_SUBSCRIPTION;
DELETE FROM SUBSCRIPTION_PACKAGE;
DELETE FROM RESOURCE;
DELETE FROM FEEDBACK;
DELETE FROM RESET_TOKENS;
DELETE FROM CUSTOMER;

-- Đặt lại chỉ số IDENTITY về 1 cho từng bảng
DBCC CHECKIDENT ('POST_COMMENT', RESEED, 0);
DBCC CHECKIDENT ('COMMUNITY_POST', RESEED, 0);
DBCC CHECKIDENT ('NOTIFICATION_PREFERENCE', RESEED, 0);
DBCC CHECKIDENT ('NOTIFICATION', RESEED, 0);
DBCC CHECKIDENT ('USER_ACHIEVEMENT', RESEED, 0);
DBCC CHECKIDENT ('ACHIEVEMENT', RESEED, 0);
DBCC CHECKIDENT ('COACHING_MESSAGE', RESEED, 0);
DBCC CHECKIDENT ('COACHING_SESSION', RESEED, 0);
DBCC CHECKIDENT ('COACH_SCHEDULE', RESEED, 0);
DBCC CHECKIDENT ('FTND_RESULT', RESEED, 0);
DBCC CHECKIDENT ('PROGRESS_TRACKER', RESEED, 0);
DBCC CHECKIDENT ('DAILY_SMOKING_SUMMARY', RESEED, 0);
DBCC CHECKIDENT ('SMOKING_LOG', RESEED, 0);
DBCC CHECKIDENT ('PLAN_FEEDBACK', RESEED, 0);
DBCC CHECKIDENT ('PLAN_MILESTONE', RESEED, 0);
DBCC CHECKIDENT ('WEEKLY_QUOTA', RESEED, 0);
DBCC CHECKIDENT ('CESSATION_PLAN', RESEED, 0);
DBCC CHECKIDENT ('PLAN_TEMPLATE', RESEED, 0);
DBCC CHECKIDENT ('COACH', RESEED, 0);
DBCC CHECKIDENT ('PAYMENT', RESEED, 0);
DBCC CHECKIDENT ('USER_SUBSCRIPTION', RESEED, 0);
DBCC CHECKIDENT ('SUBSCRIPTION_PACKAGE', RESEED, 0);
DBCC CHECKIDENT ('RESOURCE', RESEED, 0);
DBCC CHECKIDENT ('FEEDBACK', RESEED, 0);
DBCC CHECKIDENT ('RESET_TOKENS', RESEED, 0);
DBCC CHECKIDENT ('CUSTOMER', RESEED, 0);